de
name: Reusable Workflow

on:
    workflow_call: 

jobs:
    ru1-job1:

        runs-on: ubuntu-latest

        steps:
            - name: "Prueba de Mensaje de reutilzación"
              run: |
                echo "Estoyreusando un workflow one, desde Branch"
